#!/bin/sh -e
# Sometimes we need to compile a binary for $build (to run it during
# the build). We need to reset PATH so x-compiler/assembler are NOT
# in the PATH. Hence this silly script
export PATH=/bin:/usr/bin:/mingw/bin
exec ${HOSTCC:-gcc} $@
